dependencies:
  build:
    - ruby:2.5.3

build_targets:
  - name: default
    commands:
      - git submodule update --init
      - gem install bundler 
      - bundle install 
    tags:
     channel: experimental

ci:
  builds:
    - name: test
      build_target: default

